In [32]:
import pandas as pd

In [33]:
spring = pd.read_html("https://journeynorth.org/sightings/querylist.html?map=monarch-adult-first&year=2020&season=spring")
spring2020 = spring[0]

In [34]:
df.to_csv("C:/Users/t_d_o/Documents/capstone/spring2020.csv")

In [35]:
spring = pd.read_html("https://journeynorth.org/sightings/querylist.html?map=monarch-adult-first&year=2019&season=spring")
spring2019 = spring[0]

In [36]:
df.to_csv("C:/Users/t_d_o/Documents/capstone/spring2019.csv")

In [37]:
spring2019

,Unnamed: 0,Date,Town,State/Province,Latitude,Longitude,Number,Image
0,1,07/31/19,Elk Grove,CA,38.4,-121.4,1.0,NaN
1,2,07/31/19,Elk Grove,CA,38.4,-121.3,1.0,NaN
2,3,07/31/19,Florence,MS,32.1,-90.2,1.0,NaN
3,4,07/31/19,Hammond,IN,41.6,-87.5,1.0,NaN
4,5,07/31/19,Vacaville,CA,38.4,-122.0,1.0,NaN
...,...,...,...,...,...,...,...,...
2756,2757,01/04/19,Corpus Christi,TX,27.7,-97.3,1.0,NaN
2757,2758,01/04/19,Houston,TX,30.0,-95.6,1.0,NaN
2758,2759,01/04/19,Southcentral,US Virgin Islands,17.7,-64.7,2.0,NaN
2759,2760,01/02/19,Miami,FL,25.7,-80.4,2.0,NaN
2760,2761,01/01/19,Gulf Shores,AL,30.3,-87.7,1.0,NaN